language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

services:
  - mysql

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database application_test;'

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
