language: ruby
rvm:
  - 2.2.5
  - 2.3.1

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/environments/test.rb.example config/environments/test.rb

script:
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - bundle exec rake
